version: "2"
services:
  web:
    image: prakriya/prakriya-platform:v1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redis
      - neo4j
    env_file:
      - ./prakriya.env
    entrypoint:
      - /bin/sh
      - -c
      - 'npm run serve --production'
  upload:
    image: prakriya/prakriya-platform:v1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    depends_on:
      - mongodb
      - redis
      - neo4j
    env_file:
      - ./prakriya.env
    entrypoint:
      - /bin/sh
      - -c
      - 'npm run upload --production'
  mongodb:
    image: mvertes/alpine-mongo
    network_mode: host
    restart: always
    volumes:
     - $HOME/mongo/data:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"
  redis:
    image: smebberson/alpine-redis
    network_mode: host
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  neo4j:
    image: neo4j:3.1.5
    network_mode: host
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/neo4js
    cap_add:
      - SYS_RESOURCE
    expose:
      - 7474
      - 7687
      - 1337
    ports:
      - "7474:7474"
      - "7687:7687"
      - "1337:1337"
    volumes:
#      - ./neo4jContainer/neo4j/plugins:/plugins
      - ./neo4jContainer/neo4j/data:/data
#      - ./neo4jContainer/neo4j/import:/var/lib/neo4j/import
