version: "2"
services:
  web:
    image: prakriya/prakriya-platform:v1.0.0
    build: 
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redis  
    env_file:
      - ./prakriya.env
    entrypoint:
      - /bin/sh
      - -c
      - 'npm run serve --production'
  upload:
    image: prakriya/prakriya-platform:v1.0.0
    build: 
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./prakriya.env
    entrypoint:
      - /bin/sh
      - -c
      - 'npm run upload --production'
  mongodb:
    image: mvertes/alpine-mongo
    network_mode: host
    restart: always
    volumes:
     - $HOME/mongo/data:/data/db 
    expose:
      - 27017
    ports: 
      - "27017:27017"
  redis:
    image: smebberson/alpine-redis
    network_mode: host
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"    